### ISSUE TITLE
helpers/url_helper.rst

### ISSUE THREAD

**Issue by delirehberi** [yasar11732/CodeIgniter-Belge-Cevirisi#1]
Biraz iş yoğunluğum var o yüzden sayfaları tek tek üstleneceğim, şu an çevirebileceğim ilk sayfa, helpers/url_helper.rst sayfası.

**Comment by delirehberi** [comment]
Tamamlandı

**Comment by yasar11732** [comment]
Sağolasın, çevirini ekledim.
