### ISSUE TITLE
source/documentation/index.rst

### ISSUE THREAD

**Issue by yasar11732** [yasar11732/CodeIgniter-Belge-Cevirisi#3]
Bence bunu öncelikli olarak çevirmek lazım. İçerisinde rst formatıyla ilgili bilgiler var. Birileri üstlenebilir mi?

**Comment by delirehberi** [comment]
RST formatı olayı nedir tam olarak onu bile bilmiyorum. O sebeple pas diyorum :\ [ancak şu anda öğrendim sayılır :) ]

**Comment by yasar11732** [comment]
Başka biri gönüllü olmazsa, README bittikten sonra ben alacağım o zaman bunu.
